name: Build
on:
  workflow_dispatch:
  push:
    branches: [ 'master' ]
    tags:
      - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache nimble
              id: cache-nimble
              uses: actions/cache@v4
              with:
                 path: ~/.nimble
                 key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
                 restore-keys: |
                    ${{ runner.os }}-nimble-

            - uses: jiro4989/setup-nim-action@v2
              with:
                repo-token: ${{ secrets.GITHUB_TOKEN }}

            - run: nimble build -Y

            - run: nimble test -Y

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: |
                    compatibilitytool.vdf
                    icon_patch.diff
                    nativecookie
                    toolmanifest.vdf
